name: horizontal_calendar
description: A flutter plugin to show horizontal view of calendar with date picker.
version: 1.1.2
homepage: https://github.com/BwesShr/horizontal_calendar

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.18.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
